### ISSUE TITLE
static noise still appear after wake from sleep!

### ISSUE THREAD

**Issue by findyy99** [i3p9/Hackintosh-BigSur-Catalina-OpenCore-Lenovo-T450s-efi#10]
This is the log when I run the `install.sh`.

Please drag your config file to the terminal: /Volumes/文件备份/10.14迁移/Download/Hackintosh-BigSur-Catalina-OpenCore-Lenovo-T450s-efi-master/Utilities/alc_fix_swift/ALC3232.plist 

**        Removing old installs             **
**            Copying new files             **
**          Setting permissions             **
**          Loading launch daemon           **
**                                          **
**             All done. Enjoy!             **
**                                          **

**Comment by crazyi** [comment]
you can change the layout-id of applealc to 28 and update the [alcfix](https://github.com/Sniki/Lenovo-Thinkpad-T440S/tree/main/Tools)

**Comment by findyy99** [comment]
Thanks, have fixed this problem!!
