### ISSUE TITLE
Dual Battery not working

### ISSUE THREAD

**Issue by racka98** [i3p9/Hackintosh-BigSur-Catalina-OpenCore-Lenovo-T450s-efi#2]
<img width="863" alt="Screenshot 2020-10-10 at 11 12 46" src="https://user-images.githubusercontent.com/41214249/95650043-a2356c80-0ae9-11eb-95d8-1c30f586fd93.png">

I can only see one battery in there and battery life is like 2:30 hrs instead of the 4 hrs i was getting in windows

**Comment by i3p9** [comment]
Well the ACPI patches makes the two battery work together and report as one battery, as MacBooks doesn't have dual battery. So dual battery is actually working. (To test, try pulling out the external battery and it'll still run). 

battery life is bad, agreed. I also get around same battery life as you. It's possibly a power issue, and I actually plan on looking into it and make a new power management profile when I have time. In the meantime, when you're on battery, I suggest turning off Turbo Boost using an app like this one: http://tbswitcher.rugarciap.com

**Comment by i3p9** [comment]
Another thing, if you have Windows still installed, can you do some tests for me? Install Intel Power Gadget from here: https://software.intel.com/content/www/us/en/develop/articles/intel-power-gadget.html

Then on Windows, when you're on battery see how much power the laptop is consuming on idle and on load in Watts? (Windows has power modes, trying them in performance and in balanced mode should suffice). 

it'd be very beneficial if you could report these back! Thanks

**Comment by racka98** [comment]
Yeah i tried exactly this and noticed that it's just two batteries reported as one. Confirmed this with Ioreg and looking through the DSDTs. BAT0 and BAT1 are combined to a single object pointed to BATC which only reports the name of one battery to SMCBatterymanager kext (internal one)

**Comment by racka98** [comment]
> Another thing, if you have Windows still installed, can you do some tests for me? Install Intel Power Gadget from here: https://software.intel.com/content/www/us/en/develop/articles/intel-power-gadget.html
> 
> Then on Windows, when you're on battery see how much power the laptop is consuming on idle and on load in Watts? (Windows has power modes, trying them in performance and in balanced mode should suffice). 
> 
> it'd be very beneficial if you could report these back! Thanks

Sadly i nuked windows. And don't have any windows install now
