### ISSUE TITLE
Randomly getting Bad CMOS checksum when starting the laptop 

### ISSUE THREAD

**Issue by racka98** [i3p9/Hackintosh-BigSur-Catalina-OpenCore-Lenovo-T450s-efi#3]
I get this warning from time to time. I think it's the also the cause of Trackpad randomly stopping to work and randomly system freezes. Because after ny of these happen and i force restarti get that warning. Tried fixing it but can't get it to stop doing this

**Comment by i3p9** [comment]
Do you have a bugreport to show me? I haven't experienced this myself.

**Comment by racka98** [comment]
> Do you have a bugreport to show me? I haven't experienced this myself. 

Don't know how to collect it because it happens randomly. And sometimes the laptop would completely freeze so i have to force shut down. Are you on Catalina or Big Sur?

**Comment by i3p9** [comment]
I'm on Catalina but I have Big Sur installed in a external SSD to test. And honestly, I never had any touchpad issues after VoodooRMI so I can't really help without any indication of what's wrong. 

Try something, maybe switch to VoodooPS2 for touchpad, ditch VoodooRMI and see if that helps?

**Comment by racka98** [comment]
> I'm on Catalina but I have Big Sur installed in a external SSD to test. And honestly, I never had any touchpad issues after VoodooRMI so I can't really help without any indication of what's wrong. 
> 
> Try something, maybe switch to VoodooPS2 for touchpad, ditch VoodooRMI and see if that helps? 

Done some more testing and it turns out the PrtSc button disables and enables the trackpad. So that's figured out. The freezing occurs when i bang the laptop with something (like a book falling on it) so i suspect loose RAM. 

I still can't quite understand what causes the CMOS checksum error. As it's very random

**Comment by i3p9** [comment]
Yes the PrtSc button is coded into VoodooPS2Keyboard, you can change the info.plist inside it to invoke something else. 

As for CMOS, try a new CMOS battery. I almost always never shut down so I don't see the error as often.

**Comment by racka98** [comment]
> Yes the PrtSc button is coded into VoodooPS2Keyboard, you can change the info.plist inside it to invoke something else.
> 
> As for CMOS, try a new CMOS battery. I almost always never shut down so I don't see the error as often.

I never shutdown either i just noticed way to often because i was rebooting a lot in the past few days setting things up

**Comment by racka98** [comment]
> As for CMOS, try a new CMOS battery. I almost always never shut down so I don't see the error as often.

So turns out it can be fixed by setting DisableRtcChecksum kernel quirk in config.plist to true. Now i no longer have any issue when i shutdown or reboot. I've issued a PR if you don't have time to change it.

**Comment by i3p9** [comment]
Accepted. Thanks so much for figuring it out and sending a PR!
