### ISSUE TITLE
Mouse lag on dock

### ISSUE THREAD

**Issue by dheiro** [i3p9/Hackintosh-BigSur-Catalina-OpenCore-Lenovo-T450s-efi#7]
are you fix usb mouse lag when hover on dock? i think this issue appear when use high DPI mouse/gaming mouse

**Comment by racka98** [comment]
> are you fix usb mouse lag when hover on dock? i think this issue appear when use high DPI mouse/gaming mouse

Video?

**Comment by dheiro** [comment]
Solved
